/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMetaPool,
  IMetaPoolInterface,
} from "../../../contracts/interfaces/IMetaPool";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint8",
        name: "fromToken",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "tokenIndex",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "minOutputAmount",
        type: "uint256",
      },
    ],
    name: "swapExactInput",
    outputs: [
      {
        internalType: "uint256",
        name: "outputAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IMetaPool__factory {
  static readonly abi = _abi;
  static createInterface(): IMetaPoolInterface {
    return new utils.Interface(_abi) as IMetaPoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMetaPool {
    return new Contract(address, _abi, signerOrProvider) as IMetaPool;
  }
}
