/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRouting,
  IRoutingInterface,
} from "../../../contracts/interfaces/IRouting";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_fromToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_inputAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_toOwner",
        type: "address",
      },
      {
        internalType: "address",
        name: "_toToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_minimumOutputAmount",
        type: "uint256",
      },
    ],
    name: "onChainSwap",
    outputs: [
      {
        internalType: "uint256",
        name: "_outputAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_encodedVm",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "_toToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_minimumOutputAmount",
        type: "uint256",
      },
    ],
    name: "receiveAndOverride",
    outputs: [
      {
        internalType: "uint256",
        name: "_outputAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_encodedVm",
        type: "bytes",
      },
    ],
    name: "receiveAndSwap",
    outputs: [
      {
        internalType: "uint256",
        name: "_outputAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_tokenId",
        type: "uint16",
      },
      {
        internalType: "address",
        name: "_tokenContract",
        type: "address",
      },
      {
        internalType: "address",
        name: "_chainPool",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "_tokenIndexInPool",
        type: "uint8",
      },
    ],
    name: "registerToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_fromToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_inputAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_firstMinimumOutputAmount",
        type: "uint256",
      },
      {
        internalType: "uint16",
        name: "_wormholeRecipientChain",
        type: "uint16",
      },
      {
        internalType: "bytes32",
        name: "_toOwner",
        type: "bytes32",
      },
      {
        internalType: "uint16",
        name: "_toTokenId",
        type: "uint16",
      },
      {
        internalType: "uint256",
        name: "_secondMinimumOutputAmount",
        type: "uint256",
      },
    ],
    name: "swapAndTransfer",
    outputs: [
      {
        internalType: "uint64",
        name: "_wormholeSequence",
        type: "uint64",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];

export class IRouting__factory {
  static readonly abi = _abi;
  static createInterface(): IRoutingInterface {
    return new utils.Interface(_abi) as IRoutingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRouting {
    return new Contract(address, _abi, signerOrProvider) as IRouting;
  }
}
