export const SWIM_NUMBERS_COLLECTION_MAINNET =
  "9p9Bs2Ty9gGd4M5wFgt6AcbEcUxj55v5jgw13BSVEe3i";

// La croix
export const SWIM_NUMBERS_COLLECTION_DEVNET =
  "3B96d5Bt5Nnk3jv5gaaYGbXhMXsCUMcEdGGxVjjLCnvz";
