/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IUUPSUpgradeable,
  IUUPSUpgradeableInterface,
} from "../../../contracts/DeterministicFactory.sol/IUUPSUpgradeable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "newImplementation",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "upgradeToAndCall",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IUUPSUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): IUUPSUpgradeableInterface {
    return new utils.Interface(_abi) as IUUPSUpgradeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUUPSUpgradeable {
    return new Contract(address, _abi, signerOrProvider) as IUUPSUpgradeable;
  }
}
