/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFlagshipPool,
  IFlagshipPoolInterface,
} from "../../../contracts/interfaces/IFlagshipPool";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_amounts",
        type: "uint256[]",
      },
      {
        internalType: "uint8",
        name: "_outputTokenIndex",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "_minimumOutputAmount",
        type: "uint256",
      },
    ],
    name: "swap",
    outputs: [
      {
        internalType: "uint256",
        name: "_receivedSwimUSDAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFlagshipPool__factory {
  static readonly abi = _abi;
  static createInterface(): IFlagshipPoolInterface {
    return new utils.Interface(_abi) as IFlagshipPoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFlagshipPool {
    return new Contract(address, _abi, signerOrProvider) as IFlagshipPool;
  }
}
