/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type { Equalize, EqualizeInterface } from "../../contracts/Equalize";

const _abi = [
  {
    inputs: [],
    name: "MAX_AMOUNT",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608e610038600b82828239805160001a607314602b57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063d40dc870146038575b600080fd5b604667200000000000000081565b60405190815260200160405180910390f3fea264697066735822122006e6236ddcc2b8ec3a8de79460af1c5b18dcaf5358fb706caae0277d3ee7040164736f6c63430008090033";

type EqualizeConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EqualizeConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Equalize__factory extends ContractFactory {
  constructor(...args: EqualizeConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Equalize> {
    return super.deploy(overrides || {}) as Promise<Equalize>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Equalize {
    return super.attach(address) as Equalize;
  }
  override connect(signer: Signer): Equalize__factory {
    return super.connect(signer) as Equalize__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EqualizeInterface {
    return new utils.Interface(_abi) as EqualizeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Equalize {
    return new Contract(address, _abi, signerOrProvider) as Equalize;
  }
}
