/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  SwimPayload,
  SwimPayloadInterface,
} from "../../contracts/SwimPayload";

const _abi = [
  {
    inputs: [],
    name: "InvalidVersion",
    type: "error",
  },
  {
    inputs: [],
    name: "TooShort",
    type: "error",
  },
];

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212207c2db76783c62e5519212858ed6f68ece37fae57df2796e81aeb48aa666f672764736f6c63430008090033";

type SwimPayloadConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SwimPayloadConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SwimPayload__factory extends ContractFactory {
  constructor(...args: SwimPayloadConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<SwimPayload> {
    return super.deploy(overrides || {}) as Promise<SwimPayload>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): SwimPayload {
    return super.attach(address) as SwimPayload;
  }
  override connect(signer: Signer): SwimPayload__factory {
    return super.connect(signer) as SwimPayload__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SwimPayloadInterface {
    return new utils.Interface(_abi) as SwimPayloadInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SwimPayload {
    return new Contract(address, _abi, signerOrProvider) as SwimPayload;
  }
}
