/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DeterministicFactory } from "./DeterministicFactory";
export type { IUUPSUpgradeable } from "./IUUPSUpgradeable";
