/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace IRouting {
  export type TokenBalanceStruct = {
    tokenAddres: PromiseOrValue<string>;
    balance: PromiseOrValue<BigNumberish>;
  };

  export type TokenBalanceStructOutput = [string, BigNumber] & {
    tokenAddres: string;
    balance: BigNumber;
  };

  export type PoolDetailsStruct = {
    poolAddress: PromiseOrValue<string>;
    balances: IRouting.TokenBalanceStruct[];
    totalLPSupply: PromiseOrValue<BigNumberish>;
    ampFactor: PromiseOrValue<BigNumberish>;
    fees: PromiseOrValue<BigNumberish>;
  };

  export type PoolDetailsStructOutput = [
    string,
    IRouting.TokenBalanceStructOutput[],
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    poolAddress: string;
    balances: IRouting.TokenBalanceStructOutput[];
    totalLPSupply: BigNumber;
    ampFactor: BigNumber;
    fees: BigNumber;
  };
}

export interface RoutingInterface extends utils.Interface {
  functions: {
    "WORMHOLE_CORE_BRIDGE_ADDRESS()": FunctionFragment;
    "getPoolsDetails(address[])": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "onChainSwap(address,uint256,address,address,uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "receiveAndSwap(bytes,address,uint256)": FunctionFragment;
    "receiveAndSwap2(bytes)": FunctionFragment;
    "registerToken(uint16,address,address,uint8)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "swapAndTransfer(address,uint256,uint256,uint16,bytes32)": FunctionFragment;
    "swimUSD()": FunctionFragment;
    "tokenBridge()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unpause()": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "wormhole()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "WORMHOLE_CORE_BRIDGE_ADDRESS"
      | "getPoolsDetails"
      | "initialize"
      | "onChainSwap"
      | "owner"
      | "pause"
      | "paused"
      | "proxiableUUID"
      | "receiveAndSwap"
      | "receiveAndSwap2"
      | "registerToken"
      | "renounceOwnership"
      | "swapAndTransfer"
      | "swimUSD"
      | "tokenBridge"
      | "transferOwnership"
      | "unpause"
      | "upgradeTo"
      | "upgradeToAndCall"
      | "wormhole"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "WORMHOLE_CORE_BRIDGE_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolsDetails",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "onChainSwap",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receiveAndSwap",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveAndSwap2",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerToken",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapAndTransfer",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(functionFragment: "swimUSD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenBridge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "wormhole", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "WORMHOLE_CORE_BRIDGE_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolsDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onChainSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveAndSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveAndSwap2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapAndTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swimUSD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wormhole", data: BytesLike): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OnChainSwap(address,address,address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "ReceiveAndSwap(address,uint64,address,uint256)": EventFragment;
    "ReceiveAndSwap2(address,uint64,address,uint256)": EventFragment;
    "SwapAndTransfer(address,uint64,address,uint256)": EventFragment;
    "TokenRegistered(uint16,address,address)": EventFragment;
    "Unpaused(address)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OnChainSwap"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReceiveAndSwap"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReceiveAndSwap2"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapAndTransfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export interface AdminChangedEventObject {
  previousAdmin: string;
  newAdmin: string;
}
export type AdminChangedEvent = TypedEvent<
  [string, string],
  AdminChangedEventObject
>;

export type AdminChangedEventFilter = TypedEventFilter<AdminChangedEvent>;

export interface BeaconUpgradedEventObject {
  beacon: string;
}
export type BeaconUpgradedEvent = TypedEvent<
  [string],
  BeaconUpgradedEventObject
>;

export type BeaconUpgradedEventFilter = TypedEventFilter<BeaconUpgradedEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OnChainSwapEventObject {
  to: string;
  fromToken: string;
  toToken: string;
  outputAmount: BigNumber;
}
export type OnChainSwapEvent = TypedEvent<
  [string, string, string, BigNumber],
  OnChainSwapEventObject
>;

export type OnChainSwapEventFilter = TypedEventFilter<OnChainSwapEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface ReceiveAndSwapEventObject {
  from: string;
  wormholeSequence: BigNumber;
  token: string;
  amount: BigNumber;
}
export type ReceiveAndSwapEvent = TypedEvent<
  [string, BigNumber, string, BigNumber],
  ReceiveAndSwapEventObject
>;

export type ReceiveAndSwapEventFilter = TypedEventFilter<ReceiveAndSwapEvent>;

export interface ReceiveAndSwap2EventObject {
  from: string;
  wormholeSequence: BigNumber;
  token: string;
  amount: BigNumber;
}
export type ReceiveAndSwap2Event = TypedEvent<
  [string, BigNumber, string, BigNumber],
  ReceiveAndSwap2EventObject
>;

export type ReceiveAndSwap2EventFilter = TypedEventFilter<ReceiveAndSwap2Event>;

export interface SwapAndTransferEventObject {
  from: string;
  wormholeSequence: BigNumber;
  token: string;
  inputAmount: BigNumber;
}
export type SwapAndTransferEvent = TypedEvent<
  [string, BigNumber, string, BigNumber],
  SwapAndTransferEventObject
>;

export type SwapAndTransferEventFilter = TypedEventFilter<SwapAndTransferEvent>;

export interface TokenRegisteredEventObject {
  tokenId: number;
  tokenContract: string;
  chainPool: string;
}
export type TokenRegisteredEvent = TypedEvent<
  [number, string, string],
  TokenRegisteredEventObject
>;

export type TokenRegisteredEventFilter = TypedEventFilter<TokenRegisteredEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface Routing extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RoutingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    WORMHOLE_CORE_BRIDGE_ADDRESS(overrides?: CallOverrides): Promise<[string]>;

    getPoolsDetails(
      poolAddresses: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initialize(
      tokenBridgeAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onChainSwap(
      fromToken: PromiseOrValue<string>,
      inputAmount: PromiseOrValue<BigNumberish>,
      toOwner: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      minimumOutputAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    receiveAndSwap(
      encodedVm: PromiseOrValue<BytesLike>,
      toToken: PromiseOrValue<string>,
      minimumOutputAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    receiveAndSwap2(
      encodedVm: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerToken(
      tokenId: PromiseOrValue<BigNumberish>,
      tokenContract: PromiseOrValue<string>,
      chainPool: PromiseOrValue<string>,
      tokenIndexInPool: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapAndTransfer(
      fromToken: PromiseOrValue<string>,
      inputAmount: PromiseOrValue<BigNumberish>,
      firstMinimumOutputAmount: PromiseOrValue<BigNumberish>,
      wormholeRecipientChain: PromiseOrValue<BigNumberish>,
      toOwner: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swimUSD(overrides?: CallOverrides): Promise<[string]>;

    tokenBridge(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    wormhole(overrides?: CallOverrides): Promise<[string]>;
  };

  WORMHOLE_CORE_BRIDGE_ADDRESS(overrides?: CallOverrides): Promise<string>;

  getPoolsDetails(
    poolAddresses: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initialize(
    tokenBridgeAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onChainSwap(
    fromToken: PromiseOrValue<string>,
    inputAmount: PromiseOrValue<BigNumberish>,
    toOwner: PromiseOrValue<string>,
    toToken: PromiseOrValue<string>,
    minimumOutputAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  receiveAndSwap(
    encodedVm: PromiseOrValue<BytesLike>,
    toToken: PromiseOrValue<string>,
    minimumOutputAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  receiveAndSwap2(
    encodedVm: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerToken(
    tokenId: PromiseOrValue<BigNumberish>,
    tokenContract: PromiseOrValue<string>,
    chainPool: PromiseOrValue<string>,
    tokenIndexInPool: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapAndTransfer(
    fromToken: PromiseOrValue<string>,
    inputAmount: PromiseOrValue<BigNumberish>,
    firstMinimumOutputAmount: PromiseOrValue<BigNumberish>,
    wormholeRecipientChain: PromiseOrValue<BigNumberish>,
    toOwner: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swimUSD(overrides?: CallOverrides): Promise<string>;

  tokenBridge(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeTo(
    newImplementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  wormhole(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    WORMHOLE_CORE_BRIDGE_ADDRESS(overrides?: CallOverrides): Promise<string>;

    getPoolsDetails(
      poolAddresses: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<IRouting.PoolDetailsStructOutput[]>;

    initialize(
      tokenBridgeAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    onChainSwap(
      fromToken: PromiseOrValue<string>,
      inputAmount: PromiseOrValue<BigNumberish>,
      toOwner: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      minimumOutputAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    receiveAndSwap(
      encodedVm: PromiseOrValue<BytesLike>,
      toToken: PromiseOrValue<string>,
      minimumOutputAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string] & { outputAmount: BigNumber; outputToken: string }
    >;

    receiveAndSwap2(
      encodedVm: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string] & { outputAmount: BigNumber; outputToken: string }
    >;

    registerToken(
      tokenId: PromiseOrValue<BigNumberish>,
      tokenContract: PromiseOrValue<string>,
      chainPool: PromiseOrValue<string>,
      tokenIndexInPool: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    swapAndTransfer(
      fromToken: PromiseOrValue<string>,
      inputAmount: PromiseOrValue<BigNumberish>,
      firstMinimumOutputAmount: PromiseOrValue<BigNumberish>,
      wormholeRecipientChain: PromiseOrValue<BigNumberish>,
      toOwner: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swimUSD(overrides?: CallOverrides): Promise<string>;

    tokenBridge(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    wormhole(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;

    "BeaconUpgraded(address)"(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;
    BeaconUpgraded(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OnChainSwap(address,address,address,uint256)"(
      to?: PromiseOrValue<string> | null,
      fromToken?: PromiseOrValue<string> | null,
      toToken?: PromiseOrValue<string> | null,
      outputAmount?: null
    ): OnChainSwapEventFilter;
    OnChainSwap(
      to?: PromiseOrValue<string> | null,
      fromToken?: PromiseOrValue<string> | null,
      toToken?: PromiseOrValue<string> | null,
      outputAmount?: null
    ): OnChainSwapEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "ReceiveAndSwap(address,uint64,address,uint256)"(
      from?: PromiseOrValue<string> | null,
      wormholeSequence?: null,
      token?: null,
      amount?: null
    ): ReceiveAndSwapEventFilter;
    ReceiveAndSwap(
      from?: PromiseOrValue<string> | null,
      wormholeSequence?: null,
      token?: null,
      amount?: null
    ): ReceiveAndSwapEventFilter;

    "ReceiveAndSwap2(address,uint64,address,uint256)"(
      from?: PromiseOrValue<string> | null,
      wormholeSequence?: null,
      token?: null,
      amount?: null
    ): ReceiveAndSwap2EventFilter;
    ReceiveAndSwap2(
      from?: PromiseOrValue<string> | null,
      wormholeSequence?: null,
      token?: null,
      amount?: null
    ): ReceiveAndSwap2EventFilter;

    "SwapAndTransfer(address,uint64,address,uint256)"(
      from?: PromiseOrValue<string> | null,
      wormholeSequence?: null,
      token?: null,
      inputAmount?: null
    ): SwapAndTransferEventFilter;
    SwapAndTransfer(
      from?: PromiseOrValue<string> | null,
      wormholeSequence?: null,
      token?: null,
      inputAmount?: null
    ): SwapAndTransferEventFilter;

    "TokenRegistered(uint16,address,address)"(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      tokenContract?: PromiseOrValue<string> | null,
      chainPool?: null
    ): TokenRegisteredEventFilter;
    TokenRegistered(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      tokenContract?: PromiseOrValue<string> | null,
      chainPool?: null
    ): TokenRegisteredEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;

    "Upgraded(address)"(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
    Upgraded(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
  };

  estimateGas: {
    WORMHOLE_CORE_BRIDGE_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;

    getPoolsDetails(
      poolAddresses: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initialize(
      tokenBridgeAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onChainSwap(
      fromToken: PromiseOrValue<string>,
      inputAmount: PromiseOrValue<BigNumberish>,
      toOwner: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      minimumOutputAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    receiveAndSwap(
      encodedVm: PromiseOrValue<BytesLike>,
      toToken: PromiseOrValue<string>,
      minimumOutputAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    receiveAndSwap2(
      encodedVm: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerToken(
      tokenId: PromiseOrValue<BigNumberish>,
      tokenContract: PromiseOrValue<string>,
      chainPool: PromiseOrValue<string>,
      tokenIndexInPool: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapAndTransfer(
      fromToken: PromiseOrValue<string>,
      inputAmount: PromiseOrValue<BigNumberish>,
      firstMinimumOutputAmount: PromiseOrValue<BigNumberish>,
      wormholeRecipientChain: PromiseOrValue<BigNumberish>,
      toOwner: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swimUSD(overrides?: CallOverrides): Promise<BigNumber>;

    tokenBridge(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    wormhole(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    WORMHOLE_CORE_BRIDGE_ADDRESS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPoolsDetails(
      poolAddresses: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      tokenBridgeAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onChainSwap(
      fromToken: PromiseOrValue<string>,
      inputAmount: PromiseOrValue<BigNumberish>,
      toOwner: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      minimumOutputAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    receiveAndSwap(
      encodedVm: PromiseOrValue<BytesLike>,
      toToken: PromiseOrValue<string>,
      minimumOutputAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    receiveAndSwap2(
      encodedVm: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerToken(
      tokenId: PromiseOrValue<BigNumberish>,
      tokenContract: PromiseOrValue<string>,
      chainPool: PromiseOrValue<string>,
      tokenIndexInPool: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapAndTransfer(
      fromToken: PromiseOrValue<string>,
      inputAmount: PromiseOrValue<BigNumberish>,
      firstMinimumOutputAmount: PromiseOrValue<BigNumberish>,
      wormholeRecipientChain: PromiseOrValue<BigNumberish>,
      toOwner: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swimUSD(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenBridge(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    wormhole(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
