import type { TokenProject } from "@swim-io/core-types";

export enum TokenProjectId {
  Ausd = "ausd",
  Busd = "busd",
  Gmt = "gmt",
  Gst = "gst",
  Swim = "swim",
  SwimAcalaAusdLp = "swim-acala-ausd-lp",
  SwimAuroraUsdcLp = "swim-aurora-usdc-lp",
  SwimAuroraUsdtLp = "swim-aurora-usdt-lp",
  SwimAuroraUsnLp = "swim-aurora-usn-lp",
  SwimAvalancheUsdcLp = "swim-avalanche-usdc-lp",
  SwimAvalancheUsdtLp = "swim-avalanche-usdt-lp",
  SwimFantomUsdcLp = "swim-fantom-usdc-lp",
  SwimKaruraAusdLp = "swim-karura-ausd-lp",
  SwimKaruraUsdtLp = "swim-karura-usdt-lp",
  SwimPolygonUsdcLp = "swim-polygon-usdc-lp",
  SwimPolygonUsdtLp = "swim-polygon-usdt-lp",
  SwimSolanaGmtBinanceGmtLp = "swim-solana-gmt-binance-gst-lp",
  SwimSolanaGstBinanceGstLp = "swim-solana-gst-binance-gst-lp",
  SwimUsd = "swim-usd",
  Usdc = "usdc",
  Usdt = "usdt",
  Usn = "usn",
  XSwim = "xswim",
}

export const TOKEN_PROJECTS: readonly TokenProject[] = [
  {
    id: TokenProjectId.Usdc,
    symbol: "USDC",
    displayName: "USD Coin",
    // icon: USDC_SVG,
    isStablecoin: true,
    isLp: false,
  },
  {
    id: TokenProjectId.Usdt,
    symbol: "USDT",
    displayName: "Tether USD",
    // icon: USDT_SVG,
    isStablecoin: true,
    isLp: false,
  },
  {
    id: TokenProjectId.Usn,
    symbol: "USN",
    displayName: "USN",
    // icon: USN_SVG,
    isStablecoin: true,
    isLp: false,
  },
  {
    id: TokenProjectId.Busd,
    symbol: "BUSD",
    displayName: "Binance USD",
    // icon: BUSD_SVG,
    isStablecoin: true,
    isLp: false,
  },
  {
    id: TokenProjectId.Ausd,
    symbol: "aUSD",
    displayName: "Acala USD",
    // icon: AUSD_SVG,
    isStablecoin: true,
    isLp: false,
  },
  {
    id: TokenProjectId.Gst,
    symbol: "GST",
    displayName: "Green Satoshi Token",
    // icon: GST_SVG,
    isStablecoin: false,
    isLp: false,
  },
  {
    id: TokenProjectId.Gmt,
    symbol: "GMT",
    displayName: "STEPN",
    // icon: GMT_SVG,
    isStablecoin: false,
    isLp: false,
  },
  {
    id: TokenProjectId.SwimUsd,
    symbol: "swimUSD",
    displayName: "swimUSD (Swim Hexapool LP)",
    // icon: SWIM_USD_SVG,
    isStablecoin: true,
    isLp: true,
  },
  {
    id: TokenProjectId.Swim,
    symbol: "SWIM",
    displayName: "Swim Protocol Token",
    // icon: SWIM_TOKEN_SVG,
    isStablecoin: false,
    isLp: false,
  },
  {
    id: TokenProjectId.XSwim,
    symbol: "xSWIM",
    displayName: "xSWIM (SwimLake LP)",
    // icon: XSWIM_TOKEN_SVG,
    isStablecoin: false,
    isLp: true,
  },
  {
    id: TokenProjectId.SwimAvalancheUsdcLp,
    symbol: "SWIM-AVALANCHE-USDC-LP",
    displayName: "Avalanche USDC LP",
    // icon: LP_META_AVALANCHE_USDC_SVG,
    isStablecoin: false,
    isLp: true,
  },
  {
    id: TokenProjectId.SwimAvalancheUsdtLp,
    symbol: "SWIM-AVALANCHE-USDT-LP",
    displayName: "Avalanche USDT LP",
    // icon: LP_META_AVALANCHE_USDT_SVG,
    isStablecoin: false,
    isLp: true,
  },
  {
    id: TokenProjectId.SwimPolygonUsdcLp,
    symbol: "SWIM-POLYGON-USDC-LP",
    displayName: "Polygon USDC LP",
    // icon: LP_META_POLYGON_USDC_SVG,
    isStablecoin: false,
    isLp: true,
  },
  {
    id: TokenProjectId.SwimPolygonUsdtLp,
    symbol: "SWIM-POLYGON-USDT-LP",
    displayName: "Polygon USDT LP",
    // icon: LP_META_POLYGON_USDT_SVG,
    isStablecoin: false,
    isLp: true,
  },
  {
    id: TokenProjectId.SwimSolanaGstBinanceGstLp,
    symbol: "solaGST-binaGST",
    displayName: "Swim Solana GST Binance GST LP",
    // icon: LP_GST_SVG,
    isStablecoin: false,
    isLp: true,
  },
  {
    id: TokenProjectId.SwimSolanaGmtBinanceGmtLp,
    symbol: "solaGMT-binaGMT",
    displayName: "Swim Solana GMT Binance GMT LP",
    // icon: LP_GMT_SVG,
    isStablecoin: false,
    isLp: true,
  },
  {
    id: TokenProjectId.SwimAuroraUsdcLp,
    symbol: "SWIM-AURORA-USDC-LP",
    displayName: "Aurora USDC LP",
    // icon: LP_META_AURORA_USDC_SVG,
    isStablecoin: false,
    isLp: true,
  },
  {
    id: TokenProjectId.SwimAuroraUsdtLp,
    symbol: "SWIM-AURORA-USDT-LP",
    displayName: "Aurora USDT LP",
    // icon: LP_META_AURORA_USDT_SVG,
    isStablecoin: false,
    isLp: true,
  },
  {
    id: TokenProjectId.SwimAuroraUsnLp,
    symbol: "SWIM-AURORA-USN-LP",
    displayName: "Aurora USN LP",
    // icon: LP_META_AURORA_USN_SVG,
    isStablecoin: false,
    isLp: true,
  },
  {
    id: TokenProjectId.SwimFantomUsdcLp,
    symbol: "SWIM-FANTOM-USDC-LP",
    displayName: "Fantom USDC LP",
    // icon: LP_META_FANTOM_USDC_SVG,
    isStablecoin: false,
    isLp: true,
  },
  {
    id: TokenProjectId.SwimKaruraAusdLp,
    symbol: "SWIM-KARURA-AUSD-LP",
    displayName: "Karura AUSD LP",
    // icon: LP_META_KARURA_AUSD_SVG,
    isStablecoin: false,
    isLp: true,
  },
  {
    id: TokenProjectId.SwimKaruraUsdtLp,
    symbol: "SWIM-KARURA-USDT-LP",
    displayName: "Karura USDT LP",
    // icon: LP_META_KARURA_USDT_SVG,
    isStablecoin: false,
    isLp: true,
  },
  {
    id: TokenProjectId.SwimAcalaAusdLp,
    symbol: "SWIM-ACALA-AUSD-LP",
    displayName: "Acala AUSD LP",
    // icon: LP_META_ACALA_AUSD_SVG,
    isStablecoin: false,
    isLp: true,
  },
];
