name: "Verify eslint-config build"
on:
  pull_request:
    paths:
      - "packages/eslint-config/**.ts"
      - "packages/eslint-config/**.json"
  push:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packages/eslint-config

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Check format
        run: yarn format:check
      - name: Check lint
        run: yarn lint --max-warnings=0
