name: "Verify pool-math build"
on:
  pull_request:
    paths:
      - "packages/pool-math/**.ts"
      - "packages/pool-math/**.json"
      - "yarn.lock"
  push:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packages/pool-math

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Check types
        run: yarn typecheck
      - name: Check format
        run: yarn format:check
      - name: Check lint
        run: yarn lint --max-warnings=0
      - name: Test
        run: yarn test --watchAll=false
