name: "Verify wormhole build"
on:
  pull_request:
    paths:
      - "packages/wormhole/**.ts"
      - "packages/wormhole/**.json"
  push:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packages/wormhole

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build dependencies
        run: yarn workspaces foreach --topological-dev --parallel --recursive --from @swim-io/wormhole run build
      - name: Check types
        run: yarn typecheck
      - name: Check format
        run: yarn format:check
      - name: Check lint
        run: yarn lint --max-warnings=0
      - name: Test
        run: yarn test --watchAll=false
